### ISSUE TITLE
FileNotFondError

### ISSUE THREAD

**Issue by Mycolo35** [libsm64/libsm64-blender#22]
I have this message when i click in "insert Mario" 

Python: Traceback (most recent call last):
  File "C:\Users\Marina\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\libsm64-blender\__init__.py", line 57, in execute
    err = insert_mario(scene.libsm64.rom_path, scene.libsm64.mario_scale, scene.libsm64.camera_follow)
  File "C:\Users\Marina\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\libsm64-blender\mario.py", line 123, in insert_mario
    with open(os.path.expanduser(rom_path), 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\sm64.us.z64'

location: <unknown location>:-1

**Comment by jaburns** [comment]
> No such file or directory: 'c:\sm64.us.z64'

You need a ROM

**Comment by bad-droid** [comment]
it is possible to make it work for MacBook Pro (13-inch, Mid 2010), 2,4 GHz Intel Core 2 Duo
