### ISSUE TITLE
When clicked on Insert Mario, error of 'No such file or directory' is received.

### ISSUE THREAD

**Issue by NoJustAnother** [libsm64/libsm64-blender#33]
```
Python: Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\libsm64-blender\__init__.py", line 72, in execute
    err = insert_mario(scene.libsm64.rom_path, scene.libsm64.mario_scale, scene.libsm64.camera_follow)
  File "C:\Users\Dell\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\libsm64-blender\mario.py", line 123, in insert_mario
    with open(os.path.expanduser(rom_path), 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: ''

location: <unknown location>:-1
```

**Comment by jaburns** [comment]
Make sure you have a ROM and the path to it is correct. I’ll open an issue to make this error more clear.
